#!/usr/bin/env bash
# Bash script that creates a RSA key pair
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

if [ ! -d ~/.ssh ]; then
    mkdir ~/.ssh
fi
ssh-keygen -t rsa -f ~/.ssh/school -N ""
